databases:
  - name: nslwebsite
    databaseName: nsllabdb
    user: nsllab

services:
  - type: web
    name: nslwebsite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn website.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nslwebsite
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4